apiVersion: v1
kind: Pod
metadata:
  name: testpod2
  annotations: 
    description: Created a 2 containers in a single pod called testpod2

spec:
  containers:
  - name: c02
    image: ubuntu
    command: ["/bin/bash" , "-c" , "while true; do echo Hello-conatiner-co2; sleep 5; done"]
  
  - name: c03
    image: ubuntu
    command: ["/bin/bash" , "-c" , "while true; do echo Hello-container-co3; sleep 5; done"] 
  restartPolicy: Never
 