kind: ReplicaSet
apiVersion: apps/v1
metadata: 
  name: testpod7
  annotations:
    description: Using replica set  instad of replica controller
spec:
  replicas: 2
  selector:
    matchExpressions:   #These must match the labels
      - key: name  
        operator: In   
        values: [Vinit,vini,vin,vi,v]

      - key: env
        operator: NotIn
        values: [production]
  template:
    metadata:
      name: testpod7
      labels:
        name: v
      annotations:
        description: annotations instide templete????
    spec:
      containers:
        - name: c08
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo vi; sleep 5; done"]