apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  annotations:
    description: This service is used to communicate between 2 pods
spec:
  selector:
    name: testpod8
        
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

 